import { test, expect, request } from '@playwright/test';
import { inviteCaregiver } from './accounts';

test('account preference preserves both inputs across web/mobile and native-adapter dictation works in chat and organizer', async ({ page, baseURL }) => {
  const email = `input-${Date.now()}@example.test`;
  const password = 'Carestead preferred input 2026!';
  const invitation = await inviteCaregiver(baseURL!, email, 'Input Tester');
  const created = await page.request.post('/api/auth/sign-up', { headers: { Origin: baseURL! }, data: { email, password, confirmPassword: password, displayName: 'Input Tester', invitation } });
  expect(created.ok(), await created.text()).toBe(true);
  await page.goto('/tests/voice-harness.html');
  const primary = page.locator('[data-voice-primary]');
  await expect(primary).toHaveAttribute('data-voice-primary', 'true');
  expect(await page.evaluate(() => (window as any).testVoice.calls)).toBe(0);
  await page.screenshot({ path: 'test-results/mobile-voice-ready.png' });
  await page.getByRole('button', { name: /Profile settings for/ }).click();
  await page.getByRole('menuitem', { name: 'Edit profile', exact: true }).click();
  await page.getByLabel('Preferred interaction').selectOption('typing');
  await page.getByLabel('Read assistant replies aloud').uncheck();
  await page.getByRole('button', { name: 'Save changes' }).click();
  await expect(page.getByText('Profile updated.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await expect(primary).toHaveAttribute('data-voice-primary', 'false');
  const saved = await (await page.request.get('/api/state')).json();
  expect(saved.currentUser.inputPreference).toBe('typing');
  expect(saved.currentUser.spokenReplies).toBe(false);
  const otherEmail = `other-${Date.now()}@example.test`;
  const otherInvitation = await inviteCaregiver(baseURL!, otherEmail, 'Other Tester');
  const other = await request.newContext({ baseURL, extraHTTPHeaders: { Origin: baseURL! } });
  try {
    expect((await other.post('/api/auth/sign-up', { data: { email: otherEmail, password, confirmPassword: password, displayName: 'Other Tester', invitation: otherInvitation } })).ok()).toBe(true);
    const otherState = await (await other.get('/api/state')).json();
    expect(otherState.currentUser.inputPreference).toBe('voice');
    expect(otherState.currentUser.spokenReplies).toBe(true);
  } finally { await other.dispose(); }

  // Invalid preferences and attempts to target another account are rejected.
  const invalid = await page.request.post('/api/auth/update-profile', { headers: { Origin: baseURL! }, data: { displayName: 'Input Tester', inputPreference: 'invalid' } });
  expect(invalid.status()).toBe(400);
  const foreign = await page.request.post('/api/auth/update-profile', { headers: { Origin: baseURL! }, data: { displayName: 'Input Tester', accountId: 'someone-else', inputPreference: 'voice' } });
  expect(foreign.status()).toBe(400);
  await page.reload();
  await expect(primary).toHaveAttribute('data-voice-primary', 'false');
  await page.getByRole('button', { name: 'Type to Carestead', exact: true }).click();
  const message = page.getByRole('textbox', { name: /Message Carestead/ });
  await expect(message).toBeEnabled();
  await message.fill('What needs attention?');
  await page.getByRole('button', { name: 'Send message' }).click();
  await expect(page.getByText('Checking the care plan…')).toBeHidden();
  expect(await page.evaluate(() => (window as any).testVoice.spoken)).toEqual([]);
  await page.getByRole('button', { name: 'Back to voice', exact: true }).click();
  const microphone = page.getByRole('button', { name: 'Talk to Carestead', exact: true });
  await microphone.click();
  await page.evaluate(() => (window as any).testVoice.resolve('What needs attention today?'));
  await expect(microphone).toBeEnabled();
  await expect(page.getByRole('region', { name: 'Carestead voice assistant' })).toContainText('You: What needs attention today?');
  expect(await page.evaluate(() => (window as any).testVoice.spoken)).toEqual([]);
  const before = await (await page.request.get(`/api/chat?recipientId=${saved.selectedRecipient.id}`)).json();
  await microphone.click();
  await page.getByRole('button', { name: 'Cancel recording', exact: true }).click();
  await page.evaluate(() => (window as any).testVoice.resolve('Discard this recording'));
  await expect(page.getByRole('status')).toContainText('Recording cancelled. Nothing was sent.');
  expect((await (await page.request.get(`/api/chat?recipientId=${saved.selectedRecipient.id}`)).json()).messages.length).toBe(before.messages.length);

  // An empty native result must explain the failure and allow a fresh attempt.
  await microphone.click();
  await page.evaluate(() => (window as any).testVoice.resolve('   '));
  await expect(page.getByRole('status')).toContainText('No speech heard.');
  await microphone.click();
  await page.evaluate(() => (window as any).testVoice.resolve('What needs attention today?'));
  await expect(page.getByRole('region', { name: 'Carestead voice assistant' })).toContainText('You: What needs attention today?');
  await expect(page.getByRole('status')).not.toContainText('Checking your request');
  await page.getByRole('button', { name: 'Conversation history', exact: true }).click();
  await expect(page.getByText('What needs attention today?', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Back to voice', exact: true }).click();
  await page.getByRole('button', { name: 'Care Organizer', exact: true }).click();
  await page.getByRole('button', { name: 'Organize an update', exact: true }).click();
  await page.getByRole('button', { name: 'Speak an update', exact: true }).click();
  await page.evaluate(() => (window as any).testVoice.resolve('Call the care team tomorrow at 9 AM'));
  await expect(page.getByLabel('Your care update')).toHaveValue('Call the care team tomorrow at 9 AM');
  await expect(page.getByRole('button', { name: 'Organize my update' })).toBeEnabled();
  // The same account preference reaches the web entry, including voice-first.
  const updated = await page.request.post('/api/auth/update-profile', { headers: { Origin: baseURL! }, data: { displayName: 'Input Tester', inputPreference: 'voice', spokenReplies: false } });
  expect(updated.ok()).toBe(true);
  const webURL = new URL(baseURL!); webURL.port = process.env.CARESTEAD_MOBILE_TEST_BACKEND_PORT || '43980';
  await page.goto(webURL.origin);
  await expect(primary).toHaveAttribute('data-voice-primary', 'true');
  await page.getByRole('button', { name: /Ask Carestead about/ }).click();
  await expect(page.getByRole('textbox', { name: /Message Carestead/ })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Talk to Carestead', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Turn on spoken replies', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Enable spoken replies', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Mute spoken replies', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/web-assistant-panel.png' });
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: /Profile settings for/ }).click();
  await page.getByRole('menuitem', { name: 'Edit profile', exact: true }).click();
  await page.getByLabel('Start listening when mobile opens').check();
  await page.getByRole('button', { name: 'Save changes' }).click();
  await expect(page.getByText('Profile updated.', { exact: true })).toBeVisible();
  expect((await (await page.request.get('/api/state')).json()).currentUser.autoListenOnOpen).toBe(true);
  await page.goto(`${baseURL}/tests/voice-harness.html`);
  await expect(page.getByRole('button', { name: 'Cancel recording' })).toBeVisible();
  expect(await page.evaluate(() => (window as any).testVoice.calls)).toBe(1);
  await page.getByRole('button', { name: 'Cancel recording' }).click();
  await page.getByRole('button', { name: 'Type instead', exact: true }).click();
  await page.getByRole('button', { name: 'Back to voice', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Talk to Carestead', exact: true })).toBeVisible();
  expect(await page.evaluate(() => (window as any).testVoice.calls)).toBe(1);

});
