'use client';

import { useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import {
  Activity, AlertTriangle, BrainCircuit, CalendarDays, Check, CheckCircle2,
  ChevronRight, CircleUserRound, ClipboardCheck, Clock3, HeartPulse,
  LayoutDashboard, ListChecks, LoaderCircle, MemoryStick, Pill, Plus,
  Archive, BookOpen, Copy, LockKeyhole, Pencil, Route, Save, ShieldCheck,
  Sparkles, UserPlus, Users, FileText, Mail, Phone, Siren,
  Bell, Download, Trash2, Database,
} from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import type { CareTask, DashboardState, MemoryRecord, Risk, SupportContact } from '@/lib/types';

type View = 'Overview' | 'Handover' | 'Notifications' | 'Care plan' | 'Responsibilities' | 'Timeline' | 'Memory' | 'Care circle' | 'Privacy & data' | 'Evaluations';

const navItems: { label: View; icon: typeof Activity }[] = [
  { label: 'Overview', icon: LayoutDashboard },
  { label: 'Handover', icon: FileText },
  { label: 'Notifications', icon: Bell },
  { label: 'Care plan', icon: BookOpen },
  { label: 'Responsibilities', icon: ClipboardCheck },
  { label: 'Timeline', icon: CalendarDays },
  { label: 'Memory', icon: MemoryStick },
  { label: 'Care circle', icon: Users },
  { label: 'Privacy & data', icon: Database },
  { label: 'Evaluations', icon: BrainCircuit },
];

const formatDate = (value: string) =>
  new Intl.DateTimeFormat('en-CA', {
    month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit',
    timeZone: 'America/Toronto',
  }).format(new Date(value));

export default function Home() {
  const [view, setView] = useState<View>('Overview');
  const [state, setState] = useState<DashboardState | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [approvalOpen, setApprovalOpen] = useState(false);
  const [taskDialog, setTaskDialog] = useState<CareTask | 'new' | null>(null);
  const [memoryDialog, setMemoryDialog] = useState<MemoryRecord | 'new' | null>(null);
  const [memberOpen, setMemberOpen] = useState(false);
  const [recipientOpen, setRecipientOpen] = useState(false);
  const [templateOpen, setTemplateOpen] = useState(false);
  const [cloneOpen, setCloneOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  const [contactDialog, setContactDialog] = useState<SupportContact | 'new' | null>(null);
  const [consentOpen, setConsentOpen] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);

  useEffect(() => {
    let active = true;
    fetch('/api/state')
      .then((response) => {
        if (!response.ok) throw new Error('Unable to load care state');
        return response.json() as Promise<DashboardState>;
      })
      .then((nextState) => { if (active) setState(nextState); })
      .catch(() => { if (active) setMessage('The care plan could not be loaded.'); });
    return () => { active = false; };
  }, []);

  async function act(action: string, payload: Record<string, string> = {}, success: string) {
    setBusy(action);
    try {
      const response = await fetch('/api/state', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action, recipientId: state?.selectedRecipient.id, ...payload }),
      });
      const result = await response.json() as DashboardState | { error: string };
      if (!response.ok) throw new Error('error' in result ? result.error : 'Action failed');
      setState(result as DashboardState);
      setMessage(success);
      return true;
    } catch (error) {
      setMessage(error instanceof Error ? error.message : 'That action could not be completed.');
      return false;
    } finally {
      setBusy(null);
    }
  }

  async function selectRecipient(recipientId: string) {
    setBusy('switch_recipient');
    try {
      const response = await fetch(`/api/state?recipientId=${encodeURIComponent(recipientId)}`);
      const result = await response.json() as DashboardState | { error: string };
      if (!response.ok) throw new Error('error' in result ? result.error : 'Unable to switch care recipient');
      setState(result as DashboardState);
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to switch care recipient.'); }
    finally { setBusy(null); }
  }

  async function copyHandover() {
    if (!state) return;
    const openRisks = state.risks.filter((risk) => risk.status !== 'resolved');
    const reviewTasks = state.tasks.filter((task) => task.status !== 'complete').slice(0, 5);
    const lines = [
      `${state.profile.preferred_name || state.selectedRecipient.display_name} — caregiver handover`,
      state.profile.pronouns ? `Pronouns: ${state.profile.pronouns}` : '',
      `Care context: ${state.profile.care_context || 'Not yet recorded'}`,
      `Latest update: ${state.events[0] ? `${state.events[0].title} — ${state.events[0].detail}` : 'No recent events'}`,
      `Open risks: ${openRisks.length ? openRisks.map((risk) => `${risk.severity}: ${risk.title}`).join('; ') : 'None'}`,
      `Review next: ${reviewTasks.length ? reviewTasks.map((task) => `${task.title} (${task.owner})`).join('; ') : 'No open responsibilities'}`,
      `Key contacts: ${state.supportContacts.length ? state.supportContacts.map((contact) => `${contact.name}, ${contact.relationship}${contact.phone ? `, ${contact.phone}` : ''}`).join('; ') : 'None recorded'}`,
      state.profile.communication_notes ? `Communication: ${state.profile.communication_notes}` : '',
      state.profile.mobility_notes ? `Mobility: ${state.profile.mobility_notes}` : '',
      state.profile.emergency_plan ? `Urgent plan: ${state.profile.emergency_plan}` : '',
    ].filter(Boolean);
    try { await navigator.clipboard.writeText(lines.join('\n')); setMessage('Handover brief copied.'); } catch { setMessage('The handover brief could not be copied.'); }
  }

  async function downloadExport() {
    if (!state) return;
    setBusy('export');
    try {
      const response = await fetch(`/api/export?recipientId=${encodeURIComponent(state.selectedRecipient.id)}`);
      if (!response.ok) { const result = await response.json() as { error?: string }; throw new Error(result.error || 'Export failed'); }
      const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${state.selectedRecipient.display_name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-carestead-export.json`; link.click(); URL.revokeObjectURL(url); setMessage('Encrypted transport export prepared on this device.');
    } catch (error) { setMessage(error instanceof Error ? error.message : 'The export could not be prepared.'); }
    finally { setBusy(null); }
  }

  const openTasks = state?.tasks.filter((task) => task.status !== 'complete').length ?? 0;
  const resolvedRisks = state?.risks.filter((risk) => risk.status === 'resolved').length ?? 0;
  const coverage = useMemo(() => {
    if (!state?.tasks.length) return 0;
    const covered = state.tasks.filter((task) => task.owner !== 'Unassigned').length;
    return Math.round((covered / state.tasks.length) * 100);
  }, [state]);

  const pendingApproval = state?.approvals.find((approval) => approval.status === 'pending');
  const writeAllowed = state ? state.currentUser.role !== 'viewer' : false;

  return (
    <main className="min-h-screen bg-background text-foreground">
      <div className="mx-auto grid min-h-screen max-w-[1540px] lg:grid-cols-[252px_1fr]">
        <aside className="hidden border-r border-sidebar-border bg-sidebar px-5 py-6 lg:flex lg:flex-col">
          <Brand />
          <nav className="mt-9 space-y-1" aria-label="Primary navigation">
            {navItems.map(({ label, icon: Icon }) => (
              <button key={label} onClick={() => setView(label)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium transition-colors ${view === label ? 'bg-sidebar-accent text-sidebar-accent-foreground' : 'text-muted-foreground hover:bg-sidebar-accent/60 hover:text-foreground'}`}>
                <Icon className="size-[18px]" />{label}
              </button>
            ))}
          </nav>
          <div className="mt-auto rounded-2xl border border-sidebar-border bg-white/65 p-4">
            <div className="mb-3 flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Care coverage</span><span className="text-xs font-semibold text-primary">{coverage}%</span></div>
            <Progress aria-label="Care coverage percentage" value={coverage} className="[&_[data-slot=progress-indicator]]:bg-primary" />
            <p className="mt-3 text-sm font-medium">{state ? `${state.tasks.length - openTasks} of ${state.tasks.length} tasks settled` : 'Loading care plan'}</p>
            <p className="mt-1 text-xs leading-5 text-muted-foreground">Shared responsibilities stay visible and accountable.</p>
          </div>
        </aside>

        <section className="min-w-0">
          <header className="flex min-h-[76px] items-center justify-between border-b bg-background/95 px-5 py-3 backdrop-blur md:px-8">
            <div className="lg:hidden"><Brand /></div>
            <div className="hidden items-center gap-2 text-sm text-muted-foreground lg:flex"><Activity className="size-4 text-primary" />Care plan monitoring is active</div>
            <div className="flex items-center gap-3">
              {state && <select aria-label="Care recipient" value={state.selectedRecipient.id} onChange={(event) => selectRecipient(event.target.value)} disabled={!!busy} className="h-9 max-w-[170px] rounded-lg border bg-background px-3 text-sm font-medium outline-none focus:ring-2 focus:ring-ring">{state.recipients.map((recipient) => <option key={recipient.id} value={recipient.id}>{recipient.display_name}</option>)}</select>}
              <Button variant="outline" onClick={() => act('run_check', {}, 'Care plan checked and evaluation trace saved.')} disabled={!!busy || !writeAllowed}>
                {busy === 'run_check' ? <LoaderCircle className="animate-spin" /> : <Sparkles />} Run care check
              </Button>
              {state && <Button variant="ghost" size="icon" aria-label={`${state.notifications.filter((item) => !item.read_at).length} unread notifications`} onClick={() => setView('Notifications')} className="relative"><Bell />{state.notifications.some((item) => !item.read_at) && <span className="absolute top-1 right-1 size-2 rounded-full bg-[#b6533d]" />}</Button>}
              {state && <div className="hidden text-right sm:block"><p className="text-xs font-medium">{state.currentUser.displayName}</p><p className="text-[10px] capitalize text-muted-foreground">{state.currentUser.role}</p></div>}
              <span className="grid size-9 place-items-center rounded-full bg-[#d9eadf] text-sm font-semibold text-[#315944]" aria-label="Signed-in account">{state?.currentUser.displayName.slice(0, 2).toUpperCase() ?? '—'}</span>
            </div>
          </header>

          <div className="border-b px-4 py-2 lg:hidden">
            <div className="flex gap-1 overflow-x-auto">
              {navItems.map(({ label, icon: Icon }) => <button key={label} onClick={() => setView(label)} className={`flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-xs font-medium ${view === label ? 'bg-secondary text-primary' : 'text-muted-foreground'}`}><Icon className="size-4" />{label}</button>)}
            </div>
          </div>

          <div className="px-5 py-7 md:px-8 md:py-9">
            {!state ? <LoadingState /> : (
              <>
                {view === 'Overview' && <Overview state={state} openTasks={openTasks} coverage={coverage} resolvedRisks={resolvedRisks} onAdd={() => setTaskDialog('new')} onApprove={() => setApprovalOpen(true)} onAssign={() => act('assign_ride', {}, 'Maya was assigned to the physiotherapy ride.')} busy={busy} writeAllowed={writeAllowed} />}
                {view === 'Handover' && <HandoverView state={state} onEditProfile={() => setProfileOpen(true)} onAddContact={() => setContactDialog('new')} onEditContact={setContactDialog} onArchiveContact={(id) => act('archive_support_contact', { id }, 'Support contact archived.')} onCopy={copyHandover} busy={busy} />}
                {view === 'Notifications' && <NotificationsView state={state} onRead={(id) => act('mark_notification_read', { id }, 'Notification marked as read.')} onReview={() => setApprovalOpen(true)} busy={busy} />}
                {view === 'Care plan' && <CarePlanView state={state} onCreate={() => setRecipientOpen(true)} onSave={() => setTemplateOpen(true)} onClone={() => setCloneOpen(true)} onUpgrade={() => act('upgrade_plan', {}, 'The latest template version was applied without overwriting personal changes.')} busy={busy} />}
                {view === 'Responsibilities' && <Responsibilities tasks={state.tasks} onAdd={() => setTaskDialog('new')} onEdit={setTaskDialog} onComplete={(id) => act('complete_task', { id }, 'Responsibility marked complete.')} onArchive={(id) => act('archive_task', { id }, 'Responsibility archived.')} busy={busy} writeAllowed={writeAllowed} />}
                {view === 'Timeline' && <Timeline state={state} />}
                {view === 'Memory' && <Memory state={state} onAdd={() => setMemoryDialog('new')} onEdit={setMemoryDialog} onVerify={(id) => act('verify_memory', { id }, 'Trusted fact verified.')} onArchive={(id) => act('archive_memory', { id }, 'Trusted fact archived.')} writeAllowed={writeAllowed} busy={busy} />}
                {view === 'Care circle' && <CareCircle state={state} onInvite={() => setMemberOpen(true)} onRole={(id, role) => act('update_member', { id, role }, `Member role changed to ${role}.`)} onRemove={(id) => act('archive_member', { id }, 'Member removed from the care circle.')} busy={busy} />}
                {view === 'Privacy & data' && <PrivacyView state={state} onConsent={() => setConsentOpen(true)} onExport={downloadExport} onDelete={() => setDeleteOpen(true)} busy={busy} />}
                {view === 'Evaluations' && <Evaluations state={state} />}
              </>
            )}
          </div>
          <footer className="border-t px-5 py-5 text-center text-xs leading-5 text-muted-foreground md:px-8">Carestead supports care coordination only. It does not diagnose, prescribe, replace clinical judgment, or replace emergency services.</footer>
        </section>
      </div>

      <ApprovalDialog open={approvalOpen} onOpenChange={setApprovalOpen} approval={pendingApproval} busy={busy} onApprove={async () => { if (!pendingApproval) return; await act('approve_plan', { id: pendingApproval.id }, 'Plan approved. Maya now owns the medication pickup.'); setApprovalOpen(false); }} />
      <TaskDialog key={taskDialog === 'new' ? 'task-new' : `task-${taskDialog?.id ?? 'closed'}`} open={taskDialog !== null} task={taskDialog === 'new' ? undefined : taskDialog ?? undefined} onOpenChange={(open) => { if (!open) setTaskDialog(null); }} busy={busy} onSave={async (payload) => { const ok = await act(taskDialog === 'new' ? 'add_task' : 'update_task', taskDialog !== 'new' && taskDialog ? { ...payload, id: taskDialog.id } : payload, taskDialog === 'new' ? 'Responsibility added to the shared plan.' : 'Responsibility updated.'); if (ok) setTaskDialog(null); }} />
      <MemoryDialog key={memoryDialog === 'new' ? 'memory-new' : `memory-${memoryDialog?.id ?? 'closed'}`} open={memoryDialog !== null} memory={memoryDialog === 'new' ? undefined : memoryDialog ?? undefined} onOpenChange={(open) => { if (!open) setMemoryDialog(null); }} busy={busy} onSave={async (payload) => { const ok = await act(memoryDialog === 'new' ? 'add_memory' : 'update_memory', memoryDialog !== 'new' && memoryDialog ? { ...payload, id: memoryDialog.id } : payload, memoryDialog === 'new' ? 'Trusted fact added for review.' : 'Trusted fact updated.'); if (ok) setMemoryDialog(null); }} />
      <MemberDialog open={memberOpen} onOpenChange={setMemberOpen} busy={busy} onInvite={async (payload) => { const ok = await act('invite_member', payload, 'Care-circle invitation recorded.'); if (ok) setMemberOpen(false); }} />
      <CreateRecipientDialog open={recipientOpen} onOpenChange={setRecipientOpen} templates={state?.templates ?? []} busy={busy} onCreate={async (payload) => { const ok = await act('create_recipient', payload, 'A new care recipient and plan were created.'); if (ok) { setRecipientOpen(false); setView('Care plan'); } }} />
      <SaveTemplateDialog open={templateOpen} onOpenChange={setTemplateOpen} busy={busy} onSave={async (payload) => { const ok = await act('save_plan_template', payload, 'A de-identified reusable template was saved.'); if (ok) setTemplateOpen(false); }} />
      <ClonePlanDialog open={cloneOpen} onOpenChange={setCloneOpen} busy={busy} onClone={async (payload) => { const ok = await act('clone_plan', payload, 'The plan structure was cloned for a new person.'); if (ok) { setCloneOpen(false); setView('Care plan'); } }} />
      <ProfileDialog open={profileOpen} onOpenChange={setProfileOpen} profile={state?.profile} busy={busy} onSave={async (payload) => { const ok = await act('update_profile', payload, 'The handover profile was updated.'); if (ok) setProfileOpen(false); }} />
      <SupportContactDialog key={contactDialog === 'new' ? 'contact-new' : `contact-${contactDialog?.id ?? 'closed'}`} open={contactDialog !== null} contact={contactDialog === 'new' ? undefined : contactDialog ?? undefined} onOpenChange={(open) => { if (!open) setContactDialog(null); }} busy={busy} onSave={async (payload) => { const ok = await act(contactDialog === 'new' ? 'add_support_contact' : 'update_support_contact', contactDialog !== 'new' && contactDialog ? { ...payload, id: contactDialog.id } : payload, contactDialog === 'new' ? 'Support contact added.' : 'Support contact updated.'); if (ok) setContactDialog(null); }} />
      <ConsentDialog open={consentOpen} onOpenChange={setConsentOpen} consent={state?.consent} busy={busy} onSave={async (payload) => { const ok = await act('update_consent', payload, payload.consentStatus === 'active' ? 'Consent and retention settings saved.' : 'Consent withdrawn; care actions are now paused.'); if (ok) setConsentOpen(false); }} />
      <DeleteRecipientDialog open={deleteOpen} onOpenChange={setDeleteOpen} recipientName={state?.selectedRecipient.display_name ?? ''} busy={busy} onDelete={async (payload) => { const ok = await act('delete_recipient', payload, 'Recipient data was permanently deleted.'); if (ok) { setDeleteOpen(false); setView('Overview'); } }} />
      {message && <button onClick={() => setMessage(null)} className="fixed right-4 bottom-4 z-50 flex max-w-sm items-center gap-3 rounded-2xl border bg-foreground px-4 py-3 text-left text-sm text-background shadow-xl"><CheckCircle2 className="size-4 shrink-0" />{message}</button>}
    </main>
  );
}

function Brand() {
  return <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[14px] bg-primary text-primary-foreground shadow-sm"><HeartPulse className="size-5" /></span><div><p className="font-heading text-base font-semibold tracking-tight">Carestead</p><p className="text-xs text-muted-foreground">Care coordination</p></div></div>;
}

function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) {
  return <div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><p className="mb-2 text-sm font-medium text-primary">{eyebrow}</p><h1 className="font-heading text-3xl font-semibold tracking-[-0.035em] md:text-[38px]">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground md:text-base">{description}</p></div>{action}</div>;
}

function Overview({ state, openTasks, coverage, resolvedRisks, onAdd, onApprove, onAssign, busy, writeAllowed }: { state: DashboardState; openTasks: number; coverage: number; resolvedRisks: number; onAdd: () => void; onApprove: () => void; onAssign: () => void; busy: string | null; writeAllowed: boolean }) {
  return <>
    <PageHeading eyebrow={`${state.selectedRecipient.display_name}'s care plan`} title={`Good morning, ${state.currentUser.displayName}`} description={`Carestead has combined ${state.selectedRecipient.display_name}'s schedule, responsibilities, and trusted facts into one reviewable plan.`} action={<Button size="lg" className="w-fit rounded-xl px-4" onClick={onAdd} disabled={!writeAllowed}><Plus /> Add responsibility</Button>} />
    <div className="mt-8 grid gap-4 md:grid-cols-3"><Metric label="Open responsibilities" value={String(openTasks)} note="Across the shared care plan" icon={ClipboardCheck} /><Metric label="Coverage this week" value={`${coverage}%`} note="Tasks with a named owner" icon={Users} /><Metric label="Risks resolved" value={String(resolvedRisks)} note="Recorded in this demo" icon={ShieldCheck} /></div>
    <div className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(330px,0.8fr)]">
      <section><SectionHeading title="Needs your attention" subtitle="Prioritized by timing, dependency, and potential impact." /><div className="space-y-3">{state.risks.map((risk) => <RiskCard key={risk.id} risk={risk} onAction={!writeAllowed ? undefined : risk.id === 'risk-med' ? onApprove : risk.id === 'risk-ride' ? onAssign : undefined} busy={busy} />)}</div></section>
      <aside className="rounded-[22px] border bg-card p-5 shadow-[0_16px_45px_rgb(35_68_52/0.06)] md:p-6">
        <div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#e5f1e9] text-primary"><Sparkles className="size-5" /></span><div><p className="font-heading font-semibold">Agent briefing</p><p className="text-xs text-muted-foreground">Explainable care-state rules</p></div></div><Badge variant="outline" className="border-[#b9d5c3] bg-[#eff7f1] text-[#315944]">{state.events.length} events</Badge></div>
        <p className="mt-5 text-[15px] leading-6">The medication pickup is the most time-sensitive item. The agent has prepared a safe, reversible plan and is waiting for caregiver approval.</p>
        <div className="mt-5 space-y-3 border-t pt-4"><Evidence icon={Pill} text="Refill ready at the saved pharmacy" /><Evidence icon={Clock3} text="Pickup is due before 6:00 PM" /><Evidence icon={CircleUserRound} text="Maya is the usual pickup caregiver" /></div>
        <Button className="mt-5 w-full rounded-xl" onClick={onApprove} disabled={!writeAllowed || !state.approvals.some((item) => item.status === 'pending')}>Review recommended plan <ChevronRight /></Button>
        <p className="mt-3 text-center text-[11px] leading-4 text-muted-foreground">Carestead prepares actions; a caregiver approves any external or consequential step.</p>
      </aside>
    </div>
    <section className="mt-8 rounded-[22px] border bg-card p-5 md:p-6"><SectionHeading title="Upcoming care schedule" subtitle="A shared operational view for the care circle." /><div className="mt-5 grid gap-2 lg:grid-cols-4">{state.tasks.slice(0, 4).map((task) => <ScheduleCard key={task.id} task={task} />)}</div></section>
  </>;
}

function HandoverView({ state, onEditProfile, onAddContact, onEditContact, onArchiveContact, onCopy, busy }: { state: DashboardState; onEditProfile: () => void; onAddContact: () => void; onEditContact: (contact: SupportContact) => void; onArchiveContact: (id: string) => void; onCopy: () => void; busy: string | null }) {
  const writeAllowed = state.currentUser.role !== 'viewer';
  const openRisks = state.risks.filter((risk) => risk.status !== 'resolved');
  const pendingApprovals = state.approvals.filter((approval) => approval.status === 'pending');
  const factsToReview = state.memories.filter((memory) => memory.status === 'review_due');
  const openTasks = state.tasks.filter((task) => task.status !== 'complete').slice(0, 5);
  const reviewCount = openRisks.length + pendingApprovals.length + factsToReview.length;
  const profileName = state.profile.preferred_name || state.selectedRecipient.display_name;
  return <><PageHeading eyebrow="Caregiver handover" title={`${profileName}, at a glance`} description="A live, concise brief for the next caregiver—profile, current state, review priorities, responsibilities, and the people and services that keep care moving." action={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={onCopy}><Copy /> Copy brief</Button><Button onClick={onEditProfile} disabled={!writeAllowed}><Pencil /> Edit profile</Button></div>} />
    <div className="mt-8 grid gap-5 xl:grid-cols-[1.1fr_0.9fr]">
      <div className="space-y-5">
        <article className="rounded-[22px] border bg-card p-6 shadow-[0_12px_35px_rgb(35_68_52/0.05)]">
          <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-2xl bg-[#d9eadf] font-heading text-lg font-semibold text-[#315944]">{profileName.slice(0, 2).toUpperCase()}</span><div><h2 className="font-heading text-xl font-semibold">{profileName}</h2><p className="mt-1 text-sm text-muted-foreground">{state.profile.pronouns || 'Pronouns not recorded'} · {state.profile.home_base || state.selectedRecipient.timezone}</p></div></div><Badge variant="outline" className="w-fit bg-[#eff7f1] text-primary">{state.currentPlan.name}</Badge></div>
          <p className="mt-5 text-[15px] leading-7">{state.profile.care_context || 'Add a short care context so a new caregiver can understand the person and their support needs quickly.'}</p>
          <div className="mt-5 grid gap-3 sm:grid-cols-2"><ProfileNote label="How to communicate" text={state.profile.communication_notes} /><ProfileNote label="Mobility & access" text={state.profile.mobility_notes} /></div>
          {state.profile.emergency_plan && <div className="mt-4 flex gap-3 rounded-xl border border-[#e5c6bd] bg-[#fffaf8] p-4"><Siren className="mt-0.5 size-5 shrink-0 text-[#8e3d2d]" /><div><p className="text-sm font-semibold">If something is urgent</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{state.profile.emergency_plan}</p></div></div>}
        </article>

        <section className="rounded-[22px] border bg-card p-6"><div className="flex items-start justify-between gap-4"><SectionHeading title="Latest state" subtitle="The newest signal and what needs attention now." /><Badge variant="outline" className={reviewCount ? 'border-[#ead9ae] bg-[#fffdf6] text-[#7a5a12]' : 'bg-[#eff7f1] text-primary'}>{reviewCount} to review</Badge></div>
          <div className="mt-5 rounded-2xl bg-muted/55 p-4"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Most recent update</p>{state.events[0] ? <><p className="mt-2 font-heading font-semibold">{state.events[0].title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{state.events[0].detail}</p><p className="mt-2 text-xs text-muted-foreground">{formatDate(state.events[0].occurred_at)} · {state.events[0].source}</p></> : <p className="mt-2 text-sm text-muted-foreground">No recent events have been recorded.</p>}</div>
          <div className="mt-5 grid gap-3 md:grid-cols-3"><ReviewColumn title="Open risks" empty="No open risks" items={openRisks.slice(0, 3).map((risk) => ({ id: risk.id, title: risk.title, note: `${risk.severity} · ${risk.status.replace('_', ' ')}` }))} /><ReviewColumn title="Due next" empty="No open tasks" items={openTasks.slice(0, 3).map((task) => ({ id: task.id, title: task.title, note: `${task.owner} · ${formatDate(task.due_at)}` }))} /><ReviewColumn title="Verify" empty="Nothing to verify" items={[...pendingApprovals.map((approval) => ({ id: approval.id, title: approval.action, note: 'Approval pending' })), ...factsToReview.map((memory) => ({ id: memory.id, title: memory.value, note: 'Trusted fact review' }))].slice(0, 3)} /></div>
        </section>
      </div>

      <aside className="space-y-5">
        <section className="rounded-[22px] border bg-card p-6"><div className="flex items-start justify-between gap-4"><SectionHeading title="Key contacts & support" subtitle="People, providers, and services the next caregiver may need." /><Button size="sm" variant="outline" onClick={onAddContact} disabled={!writeAllowed}><Plus /> Add</Button></div><div className="mt-5 space-y-3">{state.supportContacts.length ? state.supportContacts.map((contact) => <article key={contact.id} className="rounded-2xl border bg-[#fbfcfb] p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><p className="font-heading font-semibold">{contact.name}</p>{contact.priority !== 'standard' && <Badge variant="outline" className={contact.priority === 'primary' ? 'bg-[#eff7f1] text-primary' : ''}>{contact.priority}</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{contact.relationship}{contact.organization ? ` · ${contact.organization}` : ''}</p></div>{writeAllowed && <div className="flex"><Button size="icon-sm" variant="ghost" onClick={() => onEditContact(contact)} aria-label={`Edit ${contact.name}`}><Pencil /></Button><Button size="icon-sm" variant="ghost" onClick={() => onArchiveContact(contact.id)} disabled={!!busy} aria-label={`Archive ${contact.name}`}><Archive /></Button></div>}</div>{contact.notes && <p className="mt-3 text-sm leading-6 text-muted-foreground">{contact.notes}</p>}<div className="mt-3 flex flex-wrap gap-3 text-xs">{contact.phone && <a className="flex items-center gap-1.5 text-primary hover:underline" href={`tel:${contact.phone}`}><Phone className="size-3.5" />{contact.phone}</a>}{contact.email && <a className="flex items-center gap-1.5 text-primary hover:underline" href={`mailto:${contact.email}`}><Mail className="size-3.5" />{contact.email}</a>}</div></article>) : <EmptyNote text="No support contacts recorded yet." />}</div></section>
        <section className="rounded-[22px] border bg-card p-6"><SectionHeading title="Care team with access" subtitle="People who can view or update this care plan." /><div className="mt-4 space-y-3">{state.careCircle.map((member) => <div key={member.id} className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-secondary text-xs font-semibold text-primary">{member.display_name.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{member.display_name}</p><p className="truncate text-xs text-muted-foreground">{member.email}</p></div><Badge variant="outline" className="capitalize">{member.role}</Badge></div>)}</div></section>
      </aside>
    </div>
    <p className="mt-5 text-xs leading-5 text-muted-foreground">This operational handover summarizes caregiver-entered information. It is not a medical record or substitute for emergency or clinical guidance.</p>
  </>;
}

function ProfileNote({ label, text }: { label: string; text: string }) { return <div className="rounded-xl border bg-[#fbfcfb] p-4"><p className="text-xs font-semibold text-foreground">{label}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{text || 'Not yet recorded'}</p></div>; }
function ReviewColumn({ title, items, empty }: { title: string; items: { id: string; title: string; note: string }[]; empty: string }) { return <div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.1em] text-muted-foreground">{title}</p>{items.length ? <div className="space-y-2">{items.map((item) => <div key={item.id} className="rounded-xl border p-3"><p className="line-clamp-2 text-sm font-medium leading-5">{item.title}</p><p className="mt-1 text-[11px] capitalize text-muted-foreground">{item.note}</p></div>)}</div> : <EmptyNote text={empty} />}</div>; }
function EmptyNote({ text }: { text: string }) { return <div className="rounded-xl border border-dashed p-3 text-sm text-muted-foreground">{text}</div>; }

function NotificationsView({ state, onRead, onReview, busy }: { state: DashboardState; onRead: (id: string) => void; onReview: () => void; busy: string | null }) {
  const unread = state.notifications.filter((item) => !item.read_at).length;
  return <><PageHeading eyebrow="Approval-aware inbox" title="Notifications" description="Consequential action notices remain held until the required caregiver approval. Every notification is recipient-scoped and auditable." /><div className="mt-8 flex flex-wrap gap-2"><Badge variant="outline" className="bg-[#eff7f1] text-primary">{unread} unread</Badge><Badge variant="outline">{state.notifications.filter((item) => item.delivery_state === 'needs_approval').length} awaiting approval</Badge></div><div className="mt-5 overflow-hidden rounded-[22px] border bg-card">{state.notifications.length ? state.notifications.map((item, index) => <article key={item.id} className={`flex flex-col gap-4 p-5 sm:flex-row sm:items-start ${index ? 'border-t' : ''} ${item.read_at ? 'opacity-65' : ''}`}><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${item.delivery_state === 'needs_approval' ? 'bg-[#fff4ea] text-[#8e3d2d]' : 'bg-[#e5f1e9] text-primary'}`}>{item.delivery_state === 'needs_approval' ? <ShieldCheck className="size-5" /> : <Bell className="size-5" />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-heading font-semibold">{item.title}</h3><Badge variant="outline" className="capitalize">{item.delivery_state.replaceAll('_', ' ')}</Badge>{!item.read_at && <Badge className="bg-primary text-primary-foreground">New</Badge>}</div><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.detail}</p><p className="mt-2 text-xs text-muted-foreground">{formatDate(item.created_at)}</p></div><div className="flex shrink-0 gap-2">{item.delivery_state === 'needs_approval' && <Button size="sm" onClick={onReview} disabled={!!busy}>Review approval</Button>}{!item.read_at && <Button size="sm" variant="outline" onClick={() => onRead(item.id)} disabled={!!busy}><Check /> Mark read</Button>}</div></article>) : <div className="p-8 text-center text-sm text-muted-foreground">No notifications for this care recipient.</div>}</div><div className="mt-6 flex gap-3 rounded-2xl border border-[#c8dfd0] bg-[#f8fcf9] p-5"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-primary" /><div><p className="font-heading font-semibold">Delivery policy</p><p className="mt-1 text-sm leading-6 text-muted-foreground">This release delivers notifications inside Carestead. It does not send care details by email, SMS, or lock-screen push. Approval-required actions are never represented as completed before a caregiver approves them.</p></div></div></>;
}

function PrivacyView({ state, onConsent, onExport, onDelete, busy }: { state: DashboardState; onConsent: () => void; onExport: () => void; onDelete: () => void; busy: string | null }) {
  const owner = state.currentUser.role === 'owner';
  const retention = state.consent.retention_days === '0' ? 'No automatic expiry' : `${state.consent.retention_days} days`;
  return <><PageHeading eyebrow="Privacy controls" title="Consent, retention & data" description={`Control how ${state.selectedRecipient.display_name}'s information is used, retained, exported, and permanently deleted.`} action={<Button onClick={onConsent} disabled={!owner}><Pencil /> Manage consent</Button>} />
    {state.consent.status !== 'active' && <div className="mt-6 flex gap-3 rounded-2xl border border-[#e5c6bd] bg-[#fffaf8] p-5"><Siren className="mt-0.5 size-5 shrink-0 text-[#8e3d2d]" /><div><p className="font-heading font-semibold">Consent is withdrawn</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Care-record changes, agent checks, and new notifications are paused. The owner can restore consent or permanently delete the recipient data.</p></div></div>}
    <div className="mt-8 grid gap-5 lg:grid-cols-3"><article className="rounded-[20px] border bg-card p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-secondary text-primary"><ShieldCheck className="size-5" /></span><StatusBadge value={state.consent.status} /></div><h2 className="mt-4 font-heading font-semibold">Consent record</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{state.consent.purpose}</p><p className="mt-4 text-xs text-muted-foreground">Updated {formatDate(state.consent.updated_at)}</p></article><article className="rounded-[20px] border bg-card p-5"><span className="grid size-10 place-items-center rounded-xl bg-secondary text-primary"><Clock3 className="size-5" /></span><h2 className="mt-4 font-heading font-semibold">Retention</h2><p className="mt-2 text-2xl font-heading font-semibold">{retention}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">The recorded retention choice is included in the audit history and data export.</p></article><article className="rounded-[20px] border bg-card p-5"><span className="grid size-10 place-items-center rounded-xl bg-secondary text-primary"><LockKeyhole className="size-5" /></span><h2 className="mt-4 font-heading font-semibold">Request protection</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Server-side authorization, validation, throttling, request identifiers, and privacy-safe error records protect sensitive workflows.</p><p className="mt-4 text-xs text-muted-foreground">{state.monitoring.recentErrors} handled error{state.monitoring.recentErrors === 1 ? '' : 's'} in the last 24 hours. Monitoring stores error codes—not care notes or profile text.</p></article></div>
    <section className="mt-6 rounded-[22px] border bg-card p-6"><SectionHeading title="Data requests" subtitle="Exports are recipient-scoped. Deletion requires the exact recipient name and cannot be undone." /><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border p-5"><Download className="size-5 text-primary" /><p className="mt-3 font-heading font-semibold">Export all recipient data</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Download a structured JSON package containing the profile, support network, plan, responsibilities, memory, events, risks, approvals, traces, notifications, consent, and care team.</p><Button className="mt-4" variant="outline" onClick={onExport} disabled={!owner || !!busy}>{busy === 'export' ? <LoaderCircle className="animate-spin" /> : <Download />}Download export</Button></div><div className="rounded-2xl border border-[#e5c6bd] bg-[#fffaf8] p-5"><Trash2 className="size-5 text-[#8e3d2d]" /><p className="mt-3 font-heading font-semibold">Permanently delete recipient</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Deletes the profile, support contacts, care plan, scoped operational records, consent, notifications, and access mappings. A minimal deletion-request receipt remains for accountability.</p><Button className="mt-4 text-[#8e3d2d]" variant="outline" onClick={onDelete} disabled={!owner || !!busy}><Trash2 />Start deletion</Button></div></div></section>
  </>;
}

function CarePlanView({ state, onCreate, onSave, onClone, onUpgrade, busy }: { state: DashboardState; onCreate: () => void; onSave: () => void; onClone: () => void; onUpgrade: () => void; busy: string | null }) {
  const owner = state.currentUser.role === 'owner';
  return <><PageHeading eyebrow="Portable care model" title={`${state.selectedRecipient.display_name}'s active plan`} description="Start from a proven structure, personalize it safely, and reuse the structure for someone else without carrying over private history." action={<Button onClick={onCreate} disabled={!owner || !!busy}><Plus /> New care recipient</Button>} />
    <div className="mt-8 grid gap-5 xl:grid-cols-[1.05fr_1.6fr]">
      <article className="rounded-[22px] border bg-card p-6 shadow-[0_12px_35px_rgb(35_68_52/0.05)]">
        <div className="flex items-start justify-between gap-4"><span className="grid size-11 place-items-center rounded-2xl bg-[#e5f1e9] text-primary"><BookOpen className="size-5" /></span><Badge variant="outline" className="bg-[#eff7f1] text-primary">Active</Badge></div>
        <p className="mt-5 text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">Current plan</p><h2 className="mt-1 font-heading text-xl font-semibold">{state.currentPlan.name}</h2>
        <div className="mt-5 grid grid-cols-3 gap-3"><PlanStat label="Version" value={`v${state.currentPlan.template_version}`} /><PlanStat label="Tasks" value={String(state.tasks.length)} /><PlanStat label="Overrides" value={String(state.currentPlan.override_count)} /></div>
        {state.currentPlan.update_available ? <div className="mt-5 rounded-xl border border-[#ead9ae] bg-[#fffdf6] p-4"><p className="font-medium text-[#7a5a12]">Version {state.currentPlan.latest_version} is available</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Upgrading adds new responsibilities. Your personal edits remain intact.</p><Button size="sm" className="mt-3" onClick={onUpgrade} disabled={!owner || !!busy}>{busy === 'upgrade_plan' ? <LoaderCircle className="animate-spin" /> : <Sparkles />}Review and apply</Button></div> : <p className="mt-5 flex items-center gap-2 text-sm text-primary"><CheckCircle2 className="size-4" />This plan uses the latest template.</p>}
        <div className="mt-6 flex flex-wrap gap-2"><Button variant="outline" onClick={onSave} disabled={!owner || !!busy}><Save /> Save as template</Button><Button variant="outline" onClick={onClone} disabled={!owner || !!busy}><Copy /> Clone plan</Button></div>
      </article>
      <section><SectionHeading title="Plan templates" subtitle="Four built-in starting points plus any de-identified templates your care circle saves." /><div className="mt-4 grid gap-3 md:grid-cols-2">{state.templates.map((template) => <article key={template.id} className="rounded-[18px] border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-heading font-semibold">{template.name}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{template.category.replace('-', ' ')} · version {template.version}</p></div><Badge variant="outline" className={template.source === 'custom' ? 'bg-[#fff8e8] text-[#7a5a12]' : 'bg-[#eff7f1] text-primary'}>{template.source === 'custom' ? 'Saved' : 'Built-in'}</Badge></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{template.description}</p><p className="mt-4 text-xs font-medium">{template.task_count} responsibilities · {template.rule_count} risk rules</p></article>)}</div></section>
    </div>
    <div className="mt-6 flex gap-3 rounded-2xl border border-[#c8dfd0] bg-[#f8fcf9] p-5"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-primary" /><div><p className="font-heading font-semibold">Safe portability</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Templates and clones include responsibility structure only. Trusted facts, timeline events, risks, approvals, agent traces, names, medication names, and past outcomes stay with the original person.</p></div></div>
  </>;
}

function PlanStat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-muted/55 p-3"><p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 font-heading text-lg font-semibold">{value}</p></div>; }

function Responsibilities({ tasks, onAdd, onEdit, onComplete, onArchive, busy, writeAllowed }: { tasks: CareTask[]; onAdd: () => void; onEdit: (task: CareTask) => void; onComplete: (id: string) => void; onArchive: (id: string) => void; busy: string | null; writeAllowed: boolean }) {
  return <><PageHeading eyebrow="Shared plan" title="Responsibilities" description="Create, edit, complete, reassign, or archive every care obligation." action={<Button onClick={onAdd} disabled={!writeAllowed}><Plus /> Add responsibility</Button>} /><div className="mt-8 overflow-hidden rounded-[22px] border bg-card">{tasks.map((task, index) => <div key={task.id} className={`flex flex-col gap-4 p-5 sm:flex-row sm:items-center ${index ? 'border-t' : ''}`}><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${task.status === 'complete' ? 'bg-[#e5f1e9] text-primary' : 'bg-secondary text-muted-foreground'}`}>{task.status === 'complete' ? <Check className="size-5" /> : <ListChecks className="size-5" />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-heading font-semibold">{task.title}</h3><StatusBadge value={task.status} /></div><p className="mt-1 text-sm text-muted-foreground">{formatDate(task.due_at)} · Owner: {task.owner} · {task.category}</p></div>{writeAllowed && <div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => onEdit(task)} disabled={!!busy}><Pencil /> Edit</Button>{task.status !== 'complete' && <Button variant="outline" size="sm" onClick={() => onComplete(task.id)} disabled={!!busy}><Check /> Complete</Button>}<Button variant="ghost" size="sm" onClick={() => onArchive(task.id)} disabled={!!busy} className="text-muted-foreground"><Archive /> Archive</Button></div>}</div>)}</div></>;
}

function Timeline({ state }: { state: DashboardState }) {
  return <><PageHeading eyebrow="Source activity" title="Care timeline" description="The event log shows what changed, where it came from, and when the agent considered it." /><div className="mt-8 rounded-[22px] border bg-card p-5 md:p-7"><div className="space-y-0">{state.events.map((event, index) => <div key={event.id} className="relative flex gap-4 pb-7 last:pb-0"><div className="relative z-10 grid size-10 shrink-0 place-items-center rounded-full border bg-background text-primary"><Activity className="size-4" /></div>{index < state.events.length - 1 && <span className="absolute top-10 left-5 h-[calc(100%-40px)] w-px bg-border" />}<div className="pt-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-heading font-semibold">{event.title}</h3><Badge variant="outline">{event.source}</Badge></div><p className="mt-1 text-sm leading-6 text-muted-foreground">{event.detail}</p><p className="mt-2 text-xs text-muted-foreground">{formatDate(event.occurred_at)}</p></div></div>)}</div></div></>;
}

function Memory({ state, onAdd, onEdit, onVerify, onArchive, writeAllowed, busy }: { state: DashboardState; onAdd: () => void; onEdit: (memory: MemoryRecord) => void; onVerify: (id: string) => void; onArchive: (id: string) => void; writeAllowed: boolean; busy: string | null }) {
  return <><PageHeading eyebrow="Structured memory" title="Trusted care facts" description="Review and correct the source-linked facts Carestead may reuse." action={<Button onClick={onAdd} disabled={!writeAllowed}><Plus /> Add trusted fact</Button>} /><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{state.memories.map((memory) => <article key={memory.id} className="rounded-[20px] border bg-card p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-secondary text-primary"><MemoryStick className="size-5" /></span><StatusBadge value={memory.status} /></div><p className="mt-5 text-sm font-medium leading-6">{memory.value}</p><div className="mt-5 border-t pt-4 text-xs text-muted-foreground"><p>Source · {memory.source}</p><p className="mt-1">Confidence · {memory.confidence}</p><p className="mt-1">Updated · {formatDate(memory.updated_at)}</p></div>{writeAllowed && <div className="mt-4 flex flex-wrap gap-2">{memory.status !== 'verified' && <Button size="sm" variant="outline" onClick={() => onVerify(memory.id)} disabled={!!busy}><ShieldCheck /> Verify</Button>}<Button size="sm" variant="outline" onClick={() => onEdit(memory)} disabled={!!busy}><Pencil /> Edit</Button><Button size="sm" variant="ghost" onClick={() => onArchive(memory.id)} disabled={!!busy} className="text-muted-foreground"><Archive /> Archive</Button></div>}</article>)}</div><div className="mt-6 rounded-2xl border border-[#c8dfd0] bg-[#f8fcf9] p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-primary" /><div><p className="font-heading font-semibold">Memory policy</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Only stable facts and caregiver-confirmed preferences become long-term memory. Events remain in the timeline, uncertain facts are flagged for review, and every record keeps its source.</p></div></div></div></>;
}

function CareCircle({ state, onInvite, onRole, onRemove, busy }: { state: DashboardState; onInvite: () => void; onRole: (id: string, role: string) => void; onRemove: (id: string) => void; busy: string | null }) {
  const owner = state.currentUser.role === 'owner';
  return <><PageHeading eyebrow="Authenticated workspace" title="Care circle & permissions" description="Every signed-in person receives an explicit role. Authorization is enforced by the API, not only by hidden buttons." action={<Button onClick={onInvite} disabled={!owner}><UserPlus /> Invite member</Button>} /><div className="mt-8 overflow-hidden rounded-[22px] border bg-card">{state.careCircle.map((member, index) => <div key={member.id} className={`flex flex-col gap-4 p-5 sm:flex-row sm:items-center ${index ? 'border-t' : ''}`}><span className="grid size-11 shrink-0 place-items-center rounded-full bg-secondary font-heading font-semibold text-primary">{member.display_name.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-heading font-semibold">{member.display_name}</h3><StatusBadge value={member.status} />{member.email === state.currentUser.email && <Badge variant="outline" className="bg-[#eff7f1] text-primary">You</Badge>}</div><p className="mt-1 text-sm text-muted-foreground">{member.email}</p></div><div className="flex items-center gap-2"><select aria-label={`Role for ${member.display_name}`} value={member.role} onChange={(event) => onRole(member.id, event.target.value)} disabled={!owner || member.role === 'owner' || !!busy} className="h-9 rounded-lg border bg-background px-3 text-sm capitalize outline-none focus:ring-2 focus:ring-ring">{member.role === 'owner' && <option value="owner">Owner</option>}<option value="caregiver">Caregiver</option><option value="viewer">Viewer</option></select>{owner && member.role !== 'owner' && <Button variant="ghost" size="sm" onClick={() => onRemove(member.id)} disabled={!!busy} className="text-muted-foreground"><Archive /> Remove</Button>}</div></div>)}</div><div className="mt-6 grid gap-4 md:grid-cols-3"><PermissionCard title="Owner" text="Manages members and roles, and can change all care records." /><PermissionCard title="Caregiver" text="Creates and updates responsibilities, memories, approvals, and checks." /><PermissionCard title="Viewer" text="Can review the care plan and evidence but cannot change records." /></div><div className="mt-6 flex gap-3 rounded-2xl border border-[#c8dfd0] bg-[#f8fcf9] p-5"><LockKeyhole className="mt-0.5 size-5 shrink-0 text-primary" /><div><p className="font-heading font-semibold">Identity and audit</p><p className="mt-1 text-sm leading-6 text-muted-foreground">The private Site supplies the signed-in user identity. Every mutation is checked server-side and attributed in the audit log.</p></div></div></>;
}

function PermissionCard({ title, text }: { title: string; text: string }) { return <article className="rounded-[20px] border bg-card p-5"><p className="font-heading font-semibold">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>; }

function Evaluations({ state }: { state: DashboardState }) {
  const dimensions = [{ label: 'Retrieval', value: state.benchmark.retrieval }, { label: 'Decision', value: state.benchmark.decision }, { label: 'Policy', value: state.benchmark.policy }, { label: 'Action', value: state.benchmark.action }];
  return <><PageHeading eyebrow={`Benchmark ${state.benchmark.version}`} title="Measured agent quality" description={`${state.benchmark.scenarioCount} synthetic scenarios across ${state.benchmark.categories} categories. Scores are calculated from the checked-in benchmark, not placeholders.`} /><div className="mt-8 grid gap-4 md:grid-cols-4">{dimensions.map((item) => <div key={item.label} className="rounded-[20px] border bg-card p-5"><p className="text-sm text-muted-foreground">{item.label}</p><p className="mt-2 font-heading text-3xl font-semibold">{item.value}%</p><Progress aria-label={`${item.label} evaluation score`} value={item.value} className="mt-4 [&_[data-slot=progress-indicator]]:bg-primary" /></div>)}</div><div className="mt-4 flex flex-wrap gap-2 text-xs text-muted-foreground"><Badge variant="outline" className="bg-[#eff7f1] text-primary">{state.benchmark.passed} full passes</Badge><Badge variant="outline">{state.benchmark.failed} failures for improvement</Badge><span className="py-1">Failures remain visible instead of being hidden by aggregate scores.</span></div><div className="mt-6 overflow-hidden rounded-[22px] border bg-card">{state.traces.map((trace, index) => <article key={trace.id} className={`p-5 md:p-6 ${index ? 'border-t' : ''}`}><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-heading font-semibold">{trace.trigger}</h3><Badge variant="outline" className="bg-[#eff7f1] text-primary">{trace.policy_status}</Badge></div><p className="mt-2 text-sm leading-6">{trace.decision}</p></div><span className="shrink-0 text-xs text-muted-foreground">{formatDate(trace.created_at)}</span></div><div className="mt-4 grid gap-3 rounded-xl bg-muted/55 p-4 text-xs md:grid-cols-3"><div><p className="font-semibold text-foreground">Evidence</p><p className="mt-1 leading-5 text-muted-foreground">{trace.evidence}</p></div><div><p className="font-semibold text-foreground">Tool</p><p className="mt-1 leading-5 text-muted-foreground">{trace.tool}</p></div><div><p className="font-semibold text-foreground">Outcome</p><p className="mt-1 leading-5 text-muted-foreground">{trace.outcome}</p></div></div></article>)}</div></>;
}

function Metric({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: typeof Activity }) { return <div className="rounded-[20px] border bg-card p-5 shadow-[0_8px_30px_rgb(35_68_52/0.035)]"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 font-heading text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div><span className="grid size-10 place-items-center rounded-xl bg-secondary text-primary"><Icon className="size-[19px]" /></span></div></div>; }

function SectionHeading({ title, subtitle }: { title: string; subtitle: string }) { return <div><h2 className="font-heading text-xl font-semibold tracking-tight">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{subtitle}</p></div>; }

function RiskCard({ risk, onAction, busy }: { risk: Risk; onAction?: () => void; busy: string | null }) {
  const styles = { high: 'border-[#e5c6bd] bg-[#fffaf8] text-[#8e3d2d]', medium: 'border-[#ead9ae] bg-[#fffdf6] text-[#7a5a12]', low: 'border-[#c8dfd0] bg-[#f8fcf9] text-[#315944]' }[risk.severity];
  const Icon = risk.kind === 'medication' ? Pill : risk.kind === 'transport' ? Route : CheckCircle2;
  return <article className={`flex flex-col gap-4 rounded-[20px] border p-4 transition-all hover:-translate-y-0.5 hover:shadow-md sm:flex-row sm:items-center ${styles}`}><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-white/80 shadow-sm"><Icon className="size-5" /></span><div className="min-w-0 flex-1"><p className="text-[11px] font-semibold uppercase tracking-[0.12em]">{risk.status.replace('_', ' ')}</p><h3 className="mt-1 font-heading text-[15px] font-semibold leading-5 text-foreground">{risk.title}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{risk.detail}</p></div>{onAction && risk.status !== 'resolved' && <Button variant="outline" className="shrink-0 bg-white/75 text-foreground" onClick={onAction} disabled={!!busy}>{risk.kind === 'medication' ? 'Review plan' : 'Assign ride'} <ChevronRight /></Button>}</article>;
}

function ScheduleCard({ task }: { task: CareTask }) { return <div className="rounded-2xl border bg-[#fbfcfb] p-4"><div className="flex items-center justify-between gap-3"><span className="font-heading text-sm font-semibold">{formatDate(task.due_at)}</span><StatusBadge value={task.status} /></div><p className="mt-4 text-sm font-medium leading-5">{task.title}</p><p className="mt-1 text-xs text-muted-foreground">Owner · {task.owner}</p></div>; }

function StatusBadge({ value }: { value: string }) { return <Badge variant="outline" className="bg-white text-[10px] capitalize">{value.replace('_', ' ')}</Badge>; }

function Evidence({ icon: Icon, text }: { icon: typeof Activity; text: string }) { return <div className="flex items-center gap-3 text-sm text-muted-foreground"><Icon className="size-4 shrink-0 text-primary" /><span>{text}</span></div>; }

function LoadingState() { return <div className="grid min-h-[60vh] place-items-center"><div className="text-center"><LoaderCircle className="mx-auto size-7 animate-spin text-primary" /><p className="mt-3 text-sm text-muted-foreground">Loading the shared care plan…</p></div></div>; }

function ApprovalDialog({ open, onOpenChange, approval, onApprove, busy }: { open: boolean; onOpenChange: (open: boolean) => void; approval: DashboardState['approvals'][number] | undefined; onApprove: () => void; busy: string | null }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Review medication pickup plan</DialogTitle><DialogDescription>Carestead will only record this assignment after you approve it.</DialogDescription></DialogHeader><div className="rounded-xl border border-[#e5c6bd] bg-[#fffaf8] p-4"><div className="flex gap-3"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-[#8e3d2d]" /><div><p className="font-medium">Proposed action</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{approval?.action ?? 'This plan has already been decided.'}</p></div></div></div><div className="space-y-2 text-sm"><p><strong>Why:</strong> the refill is ready and the current supply is nearly finished.</p><p><strong>Guardrail:</strong> this demo records the plan locally; it does not send messages or contact the pharmacy.</p></div><DialogFooter showCloseButton><Button onClick={onApprove} disabled={!approval || !!busy}>{busy === 'approve_plan' ? <LoaderCircle className="animate-spin" /> : <ShieldCheck />}Approve plan</Button></DialogFooter></DialogContent></Dialog>;
}

function formValue(data: FormData, name: string) { const value = data.get(name); return typeof value === 'string' ? value : ''; }
function inputDate(value?: string) { return value ? value.slice(0, 16) : ''; }

function TaskDialog({ open, task, onOpenChange, onSave, busy }: { open: boolean; task?: CareTask; onOpenChange: (open: boolean) => void; onSave: (payload: Record<string, string>) => void; busy: string | null }) {
  function submit(event: { preventDefault: () => void; currentTarget: HTMLFormElement }) { event.preventDefault(); const data = new FormData(event.currentTarget); onSave({ title: formValue(data, 'title'), owner: formValue(data, 'owner'), dueAt: formValue(data, 'dueAt'), category: formValue(data, 'category'), status: formValue(data, 'status') }); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><form onSubmit={submit}><DialogHeader><DialogTitle>{task ? 'Edit responsibility' : 'Add a responsibility'}</DialogTitle><DialogDescription>Keep the owner, timing, and operational state clear for the entire care circle.</DialogDescription></DialogHeader><div className="mt-5 grid gap-4"><label htmlFor="task-title" className="grid gap-1.5 text-sm font-medium">Responsibility<Input id="task-title" name="title" defaultValue={task?.title} placeholder="e.g. Confirm specialist referral" required /></label><div className="grid gap-4 sm:grid-cols-2"><label htmlFor="task-owner" className="grid gap-1.5 text-sm font-medium">Owner<Input id="task-owner" name="owner" defaultValue={task?.owner} placeholder="Unassigned" /></label><label htmlFor="task-category" className="grid gap-1.5 text-sm font-medium">Category<Input id="task-category" name="category" defaultValue={task?.category} placeholder="Appointment" /></label></div><div className="grid gap-4 sm:grid-cols-2"><label htmlFor="task-due" className="grid gap-1.5 text-sm font-medium">Due date and time<Input id="task-due" name="dueAt" type="datetime-local" defaultValue={inputDate(task?.due_at)} required /></label><label htmlFor="task-status" className="grid gap-1.5 text-sm font-medium">Status<select id="task-status" name="status" defaultValue={task?.status ?? 'open'} className="h-9 rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"><option value="open">Open</option><option value="due_soon">Due soon</option><option value="assigned">Assigned</option><option value="scheduled">Scheduled</option><option value="complete">Complete</option></select></label></div></div><DialogFooter className="mt-5" showCloseButton><Button type="submit" disabled={!!busy}>{busy?.includes('task') ? <LoaderCircle className="animate-spin" /> : task ? <Pencil /> : <Plus />}{task ? 'Save changes' : 'Add to plan'}</Button></DialogFooter></form></DialogContent></Dialog>;
}

function MemoryDialog({ open, memory, onOpenChange, onSave, busy }: { open: boolean; memory?: MemoryRecord; onOpenChange: (open: boolean) => void; onSave: (payload: Record<string, string>) => void; busy: string | null }) {
  function submit(event: { preventDefault: () => void; currentTarget: HTMLFormElement }) { event.preventDefault(); const data = new FormData(event.currentTarget); onSave({ value: formValue(data, 'value'), kind: formValue(data, 'kind'), source: formValue(data, 'source'), confidence: formValue(data, 'confidence'), status: formValue(data, 'status') }); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><form onSubmit={submit}><DialogHeader><DialogTitle>{memory ? 'Edit trusted fact' : 'Add a trusted fact'}</DialogTitle><DialogDescription>Every reusable fact needs a source, confidence level, and review state.</DialogDescription></DialogHeader><div className="mt-5 grid gap-4"><label htmlFor="memory-value" className="grid gap-1.5 text-sm font-medium">Fact<Input id="memory-value" name="value" defaultValue={memory?.value} placeholder="e.g. Maya usually handles pharmacy pickup" required /></label><div className="grid gap-4 sm:grid-cols-2"><label htmlFor="memory-kind" className="grid gap-1.5 text-sm font-medium">Type<Input id="memory-kind" name="kind" defaultValue={memory?.kind} placeholder="Preference" /></label><label htmlFor="memory-source" className="grid gap-1.5 text-sm font-medium">Source<Input id="memory-source" name="source" defaultValue={memory?.source} placeholder="Confirmed by caregiver" required /></label></div><div className="grid gap-4 sm:grid-cols-2"><label htmlFor="memory-confidence" className="grid gap-1.5 text-sm font-medium">Confidence<select id="memory-confidence" name="confidence" defaultValue={memory?.confidence ?? 'medium'} className="h-9 rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label htmlFor="memory-status" className="grid gap-1.5 text-sm font-medium">Status<select id="memory-status" name="status" defaultValue={memory?.status ?? 'review_due'} className="h-9 rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"><option value="review_due">Review due</option><option value="verified">Verified</option></select></label></div></div><DialogFooter className="mt-5" showCloseButton><Button type="submit" disabled={!!busy}>{busy?.includes('memory') ? <LoaderCircle className="animate-spin" /> : memory ? <Pencil /> : <Plus />}{memory ? 'Save changes' : 'Add for review'}</Button></DialogFooter></form></DialogContent></Dialog>;
}

function MemberDialog({ open, onOpenChange, onInvite, busy }: { open: boolean; onOpenChange: (open: boolean) => void; onInvite: (payload: Record<string, string>) => void; busy: string | null }) {
  function submit(event: { preventDefault: () => void; currentTarget: HTMLFormElement }) { event.preventDefault(); const data = new FormData(event.currentTarget); onInvite({ email: formValue(data, 'email'), displayName: formValue(data, 'displayName'), role: formValue(data, 'role') }); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><form onSubmit={submit}><DialogHeader><DialogTitle>Invite a care-circle member</DialogTitle><DialogDescription>Record their Carestead role here, then grant the same email access through the private Site sharing controls.</DialogDescription></DialogHeader><div className="mt-5 grid gap-4"><label htmlFor="member-name" className="grid gap-1.5 text-sm font-medium">Display name<Input id="member-name" name="displayName" placeholder="Maya" required /></label><label htmlFor="member-email" className="grid gap-1.5 text-sm font-medium">Email<Input id="member-email" name="email" type="email" placeholder="maya@example.com" required /></label><label htmlFor="member-role" className="grid gap-1.5 text-sm font-medium">Role<select id="member-role" name="role" defaultValue="caregiver" className="h-9 rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"><option value="caregiver">Caregiver — can update care records</option><option value="viewer">Viewer — read only</option></select></label></div><DialogFooter className="mt-5" showCloseButton><Button type="submit" disabled={!!busy}>{busy === 'invite_member' ? <LoaderCircle className="animate-spin" /> : <UserPlus />}Record invitation</Button></DialogFooter></form></DialogContent></Dialog>;
}

function CreateRecipientDialog({ open, onOpenChange, onCreate, templates, busy }: { open: boolean; onOpenChange: (open: boolean) => void; onCreate: (payload: Record<string, string>) => void; templates: DashboardState['templates']; busy: string | null }) {
  function submit(event: { preventDefault: () => void; currentTarget: HTMLFormElement }) { event.preventDefault(); const data = new FormData(event.currentTarget); onCreate({ displayName: formValue(data, 'displayName'), timezone: formValue(data, 'timezone'), templateKey: formValue(data, 'templateKey'), consentAccepted: formValue(data, 'consentAccepted'), nonClinicalAcknowledged: formValue(data, 'nonClinicalAcknowledged') }); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><form onSubmit={submit}><DialogHeader><DialogTitle>Create a care plan for someone</DialogTitle><DialogDescription>Choose a starting template. You can personalize every responsibility after the plan is created.</DialogDescription></DialogHeader><div className="mt-5 grid gap-4"><label htmlFor="recipient-name" className="grid gap-1.5 text-sm font-medium">Person&apos;s display name<Input id="recipient-name" name="displayName" placeholder="e.g. Jordan" required /></label><label htmlFor="recipient-timezone" className="grid gap-1.5 text-sm font-medium">Timezone<Input id="recipient-timezone" name="timezone" defaultValue="America/Toronto" required /></label><label htmlFor="recipient-template" className="grid gap-1.5 text-sm font-medium">Starting template<select id="recipient-template" name="templateKey" defaultValue={templates[0]?.template_key} className="h-9 rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring" required>{templates.map((template) => <option key={template.id} value={template.template_key}>{template.name} · v{template.version}</option>)}</select></label><label className="flex items-start gap-3 text-sm leading-5"><input name="consentAccepted" type="checkbox" className="mt-1 size-4" required /><span>I confirm that appropriate consent has been obtained for care coordination and storage.</span></label><label className="flex items-start gap-3 text-sm leading-5"><input name="nonClinicalAcknowledged" type="checkbox" className="mt-1 size-4" required /><span>I understand Carestead is not a clinical or emergency-response system.</span></label></div><DialogFooter className="mt-5" showCloseButton><Button type="submit" disabled={!!busy}>{busy === 'create_recipient' ? <LoaderCircle className="animate-spin" /> : <Plus />}Create plan</Button></DialogFooter></form></DialogContent></Dialog>;
}

function SaveTemplateDialog({ open, onOpenChange, onSave, busy }: { open: boolean; onOpenChange: (open: boolean) => void; onSave: (payload: Record<string, string>) => void; busy: string | null }) {
  function submit(event: { preventDefault: () => void; currentTarget: HTMLFormElement }) { event.preventDefault(); const data = new FormData(event.currentTarget); onSave({ name: formValue(data, 'name') }); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><form onSubmit={submit}><DialogHeader><DialogTitle>Save plan as a reusable template</DialogTitle><DialogDescription>Carestead copies the responsibility structure and removes person-specific names and medication details.</DialogDescription></DialogHeader><div className="mt-5 grid gap-4"><label htmlFor="saved-template-name" className="grid gap-1.5 text-sm font-medium">Template name<Input id="saved-template-name" name="name" placeholder="e.g. Weekly family care routine" required /></label><div className="rounded-xl border border-[#c8dfd0] bg-[#f8fcf9] p-4 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Not copied:</strong> memories, timeline events, risks, approvals, agent traces, outcomes, or care-circle membership.</div></div><DialogFooter className="mt-5" showCloseButton><Button type="submit" disabled={!!busy}>{busy === 'save_plan_template' ? <LoaderCircle className="animate-spin" /> : <Save />}Save template</Button></DialogFooter></form></DialogContent></Dialog>;
}

function ClonePlanDialog({ open, onOpenChange, onClone, busy }: { open: boolean; onOpenChange: (open: boolean) => void; onClone: (payload: Record<string, string>) => void; busy: string | null }) {
  function submit(event: { preventDefault: () => void; currentTarget: HTMLFormElement }) { event.preventDefault(); const data = new FormData(event.currentTarget); onClone({ displayName: formValue(data, 'displayName'), timezone: formValue(data, 'timezone'), consentAccepted: formValue(data, 'consentAccepted'), nonClinicalAcknowledged: formValue(data, 'nonClinicalAcknowledged') }); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><form onSubmit={submit}><DialogHeader><DialogTitle>Clone this plan for another person</DialogTitle><DialogDescription>A new care recipient receives fresh, unassigned responsibilities based on this plan.</DialogDescription></DialogHeader><div className="mt-5 grid gap-4"><label htmlFor="clone-name" className="grid gap-1.5 text-sm font-medium">New person&apos;s display name<Input id="clone-name" name="displayName" placeholder="e.g. Sam" required /></label><label htmlFor="clone-timezone" className="grid gap-1.5 text-sm font-medium">Timezone<Input id="clone-timezone" name="timezone" defaultValue="America/Toronto" required /></label><div className="rounded-xl border border-[#e5c6bd] bg-[#fffaf8] p-4 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Privacy boundary:</strong> personal facts, event history, owners, risks, approvals, and outcomes will not move.</div><label className="flex items-start gap-3 text-sm leading-5"><input name="consentAccepted" type="checkbox" className="mt-1 size-4" required /><span>I confirm consent for the new recipient&apos;s care-coordination record.</span></label><label className="flex items-start gap-3 text-sm leading-5"><input name="nonClinicalAcknowledged" type="checkbox" className="mt-1 size-4" required /><span>I understand Carestead is not a clinical or emergency-response system.</span></label></div><DialogFooter className="mt-5" showCloseButton><Button type="submit" disabled={!!busy}>{busy === 'clone_plan' ? <LoaderCircle className="animate-spin" /> : <Copy />}Clone structure</Button></DialogFooter></form></DialogContent></Dialog>;
}

function ProfileDialog({ open, onOpenChange, onSave, profile, busy }: { open: boolean; onOpenChange: (open: boolean) => void; onSave: (payload: Record<string, string>) => void; profile?: DashboardState['profile']; busy: string | null }) {
  function submit(event: { preventDefault: () => void; currentTarget: HTMLFormElement }) { event.preventDefault(); const data = new FormData(event.currentTarget); onSave({ preferredName: formValue(data, 'preferredName'), pronouns: formValue(data, 'pronouns'), homeBase: formValue(data, 'homeBase'), careContext: formValue(data, 'careContext'), communicationNotes: formValue(data, 'communicationNotes'), mobilityNotes: formValue(data, 'mobilityNotes'), emergencyPlan: formValue(data, 'emergencyPlan') }); }
  const area = 'min-h-20 w-full resize-y rounded-lg border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring';
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><form onSubmit={submit}><DialogHeader><DialogTitle>Edit handover profile</DialogTitle><DialogDescription>Keep this short and operational so another caregiver can understand the person quickly.</DialogDescription></DialogHeader><div className="mt-5 grid gap-4"><div className="grid gap-4 sm:grid-cols-3"><label htmlFor="profile-name" className="grid gap-1.5 text-sm font-medium">Preferred name<Input id="profile-name" name="preferredName" defaultValue={profile?.preferred_name} required /></label><label htmlFor="profile-pronouns" className="grid gap-1.5 text-sm font-medium">Pronouns<Input id="profile-pronouns" name="pronouns" defaultValue={profile?.pronouns} placeholder="Optional" /></label><label htmlFor="profile-home" className="grid gap-1.5 text-sm font-medium">Home base<Input id="profile-home" name="homeBase" defaultValue={profile?.home_base} placeholder="City or setting" /></label></div><label htmlFor="profile-context" className="grid gap-1.5 text-sm font-medium">Care context<textarea id="profile-context" name="careContext" defaultValue={profile?.care_context} className={area} placeholder="What should a new caregiver understand first?" /></label><div className="grid gap-4 sm:grid-cols-2"><label htmlFor="profile-communication" className="grid gap-1.5 text-sm font-medium">Communication notes<textarea id="profile-communication" name="communicationNotes" defaultValue={profile?.communication_notes} className={area} /></label><label htmlFor="profile-mobility" className="grid gap-1.5 text-sm font-medium">Mobility and access<textarea id="profile-mobility" name="mobilityNotes" defaultValue={profile?.mobility_notes} className={area} /></label></div><label htmlFor="profile-emergency" className="grid gap-1.5 text-sm font-medium">Urgent situation plan<textarea id="profile-emergency" name="emergencyPlan" defaultValue={profile?.emergency_plan} className={area} placeholder="Keep this aligned with the documented clinical or emergency plan." /></label></div><DialogFooter className="mt-5" showCloseButton><Button type="submit" disabled={!!busy}>{busy === 'update_profile' ? <LoaderCircle className="animate-spin" /> : <Save />}Save profile</Button></DialogFooter></form></DialogContent></Dialog>;
}

function SupportContactDialog({ open, onOpenChange, onSave, contact, busy }: { open: boolean; onOpenChange: (open: boolean) => void; onSave: (payload: Record<string, string>) => void; contact?: SupportContact; busy: string | null }) {
  function submit(event: { preventDefault: () => void; currentTarget: HTMLFormElement }) { event.preventDefault(); const data = new FormData(event.currentTarget); onSave({ name: formValue(data, 'name'), relationship: formValue(data, 'relationship'), contactType: formValue(data, 'contactType'), phone: formValue(data, 'phone'), email: formValue(data, 'email'), organization: formValue(data, 'organization'), notes: formValue(data, 'notes'), priority: formValue(data, 'priority') }); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><form onSubmit={submit}><DialogHeader><DialogTitle>{contact ? 'Edit support contact' : 'Add a support contact'}</DialogTitle><DialogDescription>Include the people, providers, and services another caregiver may need during a handover.</DialogDescription></DialogHeader><div className="mt-5 grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><label htmlFor="support-name" className="grid gap-1.5 text-sm font-medium">Name<Input id="support-name" name="name" defaultValue={contact?.name} required /></label><label htmlFor="support-relationship" className="grid gap-1.5 text-sm font-medium">Role or relationship<Input id="support-relationship" name="relationship" defaultValue={contact?.relationship} placeholder="Family caregiver, pharmacy…" required /></label></div><div className="grid gap-4 sm:grid-cols-2"><label htmlFor="support-type" className="grid gap-1.5 text-sm font-medium">Type<select id="support-type" name="contactType" defaultValue={contact?.contact_type ?? 'person'} className="h-9 rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"><option value="person">Person</option><option value="provider">Provider</option><option value="service">Service</option></select></label><label htmlFor="support-priority" className="grid gap-1.5 text-sm font-medium">Priority<select id="support-priority" name="priority" defaultValue={contact?.priority ?? 'standard'} className="h-9 rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"><option value="primary">Primary</option><option value="important">Important</option><option value="standard">Standard</option></select></label></div><label htmlFor="support-org" className="grid gap-1.5 text-sm font-medium">Organization<Input id="support-org" name="organization" defaultValue={contact?.organization} placeholder="Optional" /></label><div className="grid gap-4 sm:grid-cols-2"><label htmlFor="support-phone" className="grid gap-1.5 text-sm font-medium">Phone<Input id="support-phone" name="phone" type="tel" defaultValue={contact?.phone} /></label><label htmlFor="support-email" className="grid gap-1.5 text-sm font-medium">Email<Input id="support-email" name="email" type="email" defaultValue={contact?.email} /></label></div><label htmlFor="support-notes" className="grid gap-1.5 text-sm font-medium">What they help with<textarea id="support-notes" name="notes" defaultValue={contact?.notes} className="min-h-20 w-full resize-y rounded-lg border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring" /></label></div><DialogFooter className="mt-5" showCloseButton><Button type="submit" disabled={!!busy}>{busy?.includes('support_contact') ? <LoaderCircle className="animate-spin" /> : contact ? <Pencil /> : <Plus />}{contact ? 'Save contact' : 'Add contact'}</Button></DialogFooter></form></DialogContent></Dialog>;
}

function ConsentDialog({ open, onOpenChange, onSave, consent, busy }: { open: boolean; onOpenChange: (open: boolean) => void; onSave: (payload: Record<string, string>) => void; consent?: DashboardState['consent']; busy: string | null }) {
  function submit(event: { preventDefault: () => void; currentTarget: HTMLFormElement }) { event.preventDefault(); const data = new FormData(event.currentTarget); onSave({ consentStatus: formValue(data, 'consentStatus'), retentionDays: formValue(data, 'retentionDays'), purpose: formValue(data, 'purpose'), nonClinicalAcknowledged: formValue(data, 'nonClinicalAcknowledged') }); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-xl"><form onSubmit={submit}><DialogHeader><DialogTitle>Manage consent and retention</DialogTitle><DialogDescription>Consent changes are attributed in the audit record. Withdrawing consent pauses care-data changes and agent checks.</DialogDescription></DialogHeader><div className="mt-5 grid gap-4"><label htmlFor="consent-status" className="grid gap-1.5 text-sm font-medium">Consent status<select id="consent-status" name="consentStatus" defaultValue={consent?.status ?? 'active'} className="h-9 rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"><option value="active">Active</option><option value="withdrawn">Withdrawn — pause processing</option></select></label><label htmlFor="retention-days" className="grid gap-1.5 text-sm font-medium">Retention period<select id="retention-days" name="retentionDays" defaultValue={consent?.retention_days ?? '365'} className="h-9 rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"><option value="30">30 days</option><option value="90">90 days</option><option value="365">365 days</option><option value="0">No automatic expiry</option></select></label><label htmlFor="consent-purpose" className="grid gap-1.5 text-sm font-medium">Permitted purpose<textarea id="consent-purpose" name="purpose" defaultValue={consent?.purpose} className="min-h-24 w-full resize-y rounded-lg border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring" required /></label><label className="flex items-start gap-3 text-sm leading-5"><input name="nonClinicalAcknowledged" type="checkbox" className="mt-1 size-4" required /><span>I understand Carestead supports coordination only and does not provide clinical decisions or emergency response.</span></label></div><DialogFooter className="mt-5" showCloseButton><Button type="submit" disabled={!!busy}>{busy === 'update_consent' ? <LoaderCircle className="animate-spin" /> : <ShieldCheck />}Save controls</Button></DialogFooter></form></DialogContent></Dialog>;
}

function DeleteRecipientDialog({ open, onOpenChange, onDelete, recipientName, busy }: { open: boolean; onOpenChange: (open: boolean) => void; onDelete: (payload: Record<string, string>) => void; recipientName: string; busy: string | null }) {
  function submit(event: { preventDefault: () => void; currentTarget: HTMLFormElement }) { event.preventDefault(); const data = new FormData(event.currentTarget); onDelete({ confirmName: formValue(data, 'confirmName') }); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><form onSubmit={submit}><DialogHeader><DialogTitle>Permanently delete {recipientName}</DialogTitle><DialogDescription>This cannot be undone. Care records, profile, contacts, plan, consent, notifications, and access assignments will be removed.</DialogDescription></DialogHeader><div className="mt-5 rounded-xl border border-[#e5c6bd] bg-[#fffaf8] p-4 text-sm leading-6 text-muted-foreground">An accountability receipt records that a verified deletion occurred, but it does not retain the deleted care content.</div><label htmlFor="delete-confirm" className="mt-4 grid gap-1.5 text-sm font-medium">Type <strong>{recipientName}</strong> to confirm<Input id="delete-confirm" name="confirmName" autoComplete="off" required /></label><DialogFooter className="mt-5" showCloseButton><Button type="submit" variant="destructive" disabled={!!busy}>{busy === 'delete_recipient' ? <LoaderCircle className="animate-spin" /> : <Trash2 />}Permanently delete</Button></DialogFooter></form></DialogContent></Dialog>;
}
